# Setup
title:               "Patrick Kiel"
tagline:             "An Open Lab Notebook"
description:         "Patrick Kiel's open science notebook detailing analyses and methods in his biophysical and structural investigations of corals."
url:                 "https://patrickkiel.com"
baseurl:             "/notebook"
paginate:            3
permalink:            /:categories/:title/

# About/contact
author:
  name:              Patrick Kiel
  url:               "https://patrickkiel.com"
  email:             "pkiel@rsmas.miami.edu"
  twitter_username: "patrickmkiel"
  github_username: "pkiel"

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y



