---
layout: post
title:  "Testing Javascript Passwords"
author: "Patrick M Kiel"
date: '`r Sys.Date()`'
categories: [methods]
description: "Here I am testing Javascript enabled passwords of content on my blog"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_file = paste0(Sys.Date(), "-",
                        gsub(pattern = "\\.Rmd$",
                              "", basename(inputFile))
                        ,".md"), 
  output_dir = "../_posts") })
always_allow_html: true
---

```{r setup, include=FALSE, cache=FALSE}
#load packages
library(tidyverse)
library(kableExtra)
library(leaflet)
library(rgdal)
library(htmlwidgets)

base_dir <- "C:/Users/pkiel/Github/notebook/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/notebook/" # subdirectory of patrickmkiel.com
fig_path <- "images/"

  # Set base directories
  knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
  
  # Set figure directories
  knitr::opts_chunk$set(fig.path = fig_path,
                      cache.path = '../cache/',
                      message=FALSE, warning=FALSE,
                      cache = FALSE)
  
  #knitr Chunk Hook to Wrap for Hidden Div
#   knit_hooks$set(wrap = function(before, options, envir){
#   if (before){
#     paste0('<', options$wrap, 'id=', options$ '>')
#   } else {
#     paste0('</', options$wrap, '>')
#   }
# })
```

```{js, echo=FALSE}
function verify() {
  if (document.getElementById('password').value === 'password') {
    document.getElementById('HIDDENDIV').classList.remove("hidden"); 
    document.getElementById('credentials').classList.add("hidden"); // Hide the div containing the credentials
  } else {
    alert('Invalid Password!');
    password.setSelectionRange(0, password.value.length);
  }
  return false;
}
```

```{css, echo=FALSE}
.hidden {
  display: none;
}
```

<!-- The password box -->
<div id="credentials">
  <input type="text" id="password" onkeydown="if (event.keyCode == 13) verify()" />
  <br/>
  <input id="button" type="button" value="Show Content" onclick="verify()" />
</div>

<!-- The content we want to show after password -->
<div id="HIDDENDIV" class="hidden">
```{r tesing, echo=F}
mtcars %>%
  ggplot(aes(cyl,mpg)) +
  geom_point() +
  theme_classic()
```


</div>
